<?php 
$_attributeSplashs = $this->getAttributeSplashs();
$featured = $this->getFeaturedAttributeSplashs();
?>

<div class="featured-designers">
    <ul>
        <?php foreach($featured as $_fAttributeSplash):?>
            <li>
        		<?php if($_fAttributeSplash->getUrlKey()):?>
        			<a href="<?= $this->getAttributeSplashURL($_fAttributeSplash->getUrlKey()) ?>">
        		<?php endif;?>
        		
        		<?php if($_fAttributeSplash->getThumbnail()):?>
        	        <span class="image">
        			    <img class="f-attributesplash-img" src="<?= $this->getAttributeSplashImageURL($_fAttributeSplash->getThumbnail()) ?>" title="<?= $_fAttributeSplash->getName();?>" alt="<?= $_fAttributeSplash->getName();?>" width="150" height="150" />
        	        </span>
        		<?php endif; ?>
        		
        		<span class="attributesplash-title">
        			<?= $_fAttributeSplash->getName();?>
        		</span>
        		
        		<?php if($_fAttributeSplash->getUrlKey()):?>
        	        </a>
        	    <?php endif;?>
            </li>
        <?php endforeach;?>
    </ul>
</div>

<div id="shopby-group-page">
    <div class="page-list">   
        <div class="page-head">
            <h3><?= __("Designer") ?></h3>
        </div>
        <?php foreach (range('0', '9') as $char) : ?>
        	<?php if(isset($_attributeSplashs[$char])):?>
        		<div class="brand-char">
        			<strong><?= $char;?></strong>
        			<ul>
        			<?php foreach($_attributeSplashs[$char] as $_attributeSplash):?>
        				<li>
        					<?php if($_attributeSplash->getUrlKey()):?>
        						<a href="<?= $this->getAttributeSplashURL($_attributeSplash->getUrlKey()) ?>"><?= $_attributeSplash->getName();?></a>
        					<?php endif;?>
        				</li>
        			<?php endforeach;?>
        			</ul>
        		</div>
        	<?php endif;?>
        <?php endforeach;?>
        
        <div class="content">
            <?php $i=0 ?>
            <?php foreach (range('A', 'Z') as $char) :?>
            	<?php if(isset($_attributeSplashs[$char])):?>
            		<div class="attributesplash-char">
            			<strong> <?= $char;?></strong>
            			<ul>
            			<?php foreach($_attributeSplashs[$char] as $_attributeSplas):?>
            				<li>
            					<?php if($_attributeSplas->getUrlKey()):?>
            						<a href="<?= $this->getAttributeSplashURL($_attributeSplas->getUrlKey()) ?>"><?= $_attributeSplas->getName();?></a>
            					<?php endif;?>
            				</li>
            			<?php endforeach;?>
            			</ul>
            		</div>
            		<?php 
                        $i++; 
                        if($i%6 == 0 ){
                            echo '<div class="breaker"></div>';
                        }
                    ?>
            	<?php endif;?>
            <?php endforeach;?>
        </div>
        
    </div>
</div>